### ISSUE TITLE
 [Question] Why don't we call MarsWrapperGps::RunCoreStatePublisher() in MarsWrapperGps::ImuMeasurementCallback(...)

### ISSUE THREAD

**Issue by dantenoguera** [aau-cns/mars_ros#2]
Hi! As the title says shoudn't this:

https://github.com/aau-cns/mars_ros/blob/834ad792a5f62565cf8869cab7db2c8d491d2093/src/mars_wrapper_gps.cpp#L164-L172

be like this:

https://github.com/aau-cns/mars_ros/blob/834ad792a5f62565cf8869cab7db2c8d491d2093/src/mars_wrapper_pose.cpp#L168-L171

**Comment by Chris-Bee** [comment]
Hello @dantenoguera, that's a very good idea. Our internal version already has this modification among other features and improvements. This will go online by this week, together with the open-sourcing of our flight stack code (See the paper FYI: https://ieeexplore.ieee.org/document/9849131).

**Comment by Chris-Bee** [comment]
@dantenoguera as mentioned above, the changes you mentioned have been part of our latest development stage and are now present in the development branch. Hope this helps.

**Comment by dantenoguera** [comment]
Awesome
